CREATE TABLE PET_CARE_LOG (
    PRODUCT_ID NUMBER(10) NOT NULL,
    LOG_DATETIME DATE DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY_USER VARCHAR2(30) NOT NULL,
    LOG_TEXT VARCHAR2(500),
    LAST_UPDATE_DATETIME DATE,

    CONSTRAINT PK_PET_CARE_LOG 
    PRIMARY KEY (PRODUCT_ID, LOG_DATETIME)
);
ALTER TABLE PET_CARE_LOG
ADD (
    UPDATED_BY_USER VARCHAR2(30),
    UPDATE_DATE DATE
);


CREATE OR REPLACE TRIGGER trg_pet_care_log_bi
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.LOG_DATETIME := SYSDATE;
    :NEW.CREATED_BY_USER := USER;
END;


CREATE OR REPLACE TRIGGER trg_pet_care_log_bu
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN 
    IF :OLD.UPDATED_BY_USER != USER THEN
    :NEW.PRODUCT_ID := :OLD.PRODUCT_ID;
        :NEW.LOG_DATETIME := :OLD.LOG_DATETIME;
        :NEW.CREATED_BY_USER := :OLD.CREATED_BY_USER;
        :NEW.LOG_TEXT := :OLD.LOG_TEXT;
        :NEW.LAST_UPDATE_DATETIME := :OLD.LAST_UPDATE_DATETIME;
        :NEW.UPDATED_BY_USER := :OLD.UPDATED_BY_USER;
    ELSE
        :NEW.UPDATED_BY_USER := USER;
        :NEW.LAST_UPDATE_DATETIME := SYSDATE;
    END IF;
END;


CREATE OR REPLACE TRIGGER trg_pet_care_log_bd
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER = 'JOEMANAGER' THEN
        NULL;
    ELSE
        NULL;
    END IF;
END;